company:
  property: User Profile Dev


spring:
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: approle
      app-role:
        role-id: f41545fb-d814-1274-edb5-7ae53d250e84
        secret-id: 5d39eb23-b339-9b76-434d-2c196cd706c7
      kv:
        enabled: true
        backend: one360
        default-context: company-service/dev
        generic:
          enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/one-test
    driver-class-name: org.postgresql.Driver
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true